"""empty message

Revision ID: 63582a4d3bdc
Revises: 9079ab5a304b
Create Date: 2023-09-22 15:08:52.070234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63582a4d3bdc'
down_revision = '9079ab5a304b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('checked')

    # ### end Alembic commands ###
